name: Build & Publish

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      fullbuild:
        type: boolean
        description: Perform a full build
        default: false
    
jobs:
  build:
    runs-on: windows-2022
    env:
      BUILD_CONFIG: "Release"
      DOTNET_VER: "net9.0-windows7.0"
      APP_DIR: "EM.HostsManager.App"
      INSTALLER_DIR: "EM.HostsManager.Installer"
      SIGNTOOL: "C:/Program Files (x86)/Windows Kits/10/bin/10.0.22621.0/x86/signtool.exe"  # See list of installed Windows SDK's @ https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
      TIMESTAMP_URL: "http://timestamp.digicert.com"

    steps:
    - uses: actions/checkout@v4
    
    - name: Fetch all history and tags
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      run: |
        git fetch --unshallow --prune

    - name: Install GitVersion
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      uses: gittools/actions/gitversion/setup@v3.0.2
      with:
        versionSpec: '5.x'
        includePrerelease: false
  
    - name: Determine Version
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.0.2
      with:
        useConfigFile: true
        configFilePath: 'GitVersion.yml'
        additionalArguments: '-ensureassemblyinfo'

    - name: Display Version
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      shell: powershell
      run: |
        Write-Output "==============================================================================================================================================="
        Write-Output "Version : ${{ steps.gitversion.outputs.MajorMinorPatch }}"
        Write-Output "==============================================================================================================================================="

    - name: Setup .NET 9.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Debug Build (For Tests)
      run: dotnet build "./src" --configuration Debug

    - name: Run Tests [Unit]
      run: dotnet test "./src" --configuration Debug --verbosity normal --filter Category=Unit
  
    - name: Run Tests [Integration]
      run: dotnet test "./src" --configuration Debug --verbosity normal --filter Category=Integration
    
    - name: Run Tests [Mock]
      run: dotnet test "./src" --configuration Debug --verbosity normal --filter Category=Mock

    - name: Clean
      run: dotnet clean "./src"

    - name: Patch BuildDateAttribute
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      shell: powershell
      run: |
        Write-Output "==============================================================================================================================================="
        Write-Output "Pre build. Patching BuildDate Attribute..."
        Write-Output "==============================================================================================================================================="
        $buildDateAttribute = [DateTime]::UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fffZ")
        Write-Output "Using: '$buildDateAttribute'"
        $dir = "./src/${{ env.APP_DIR }}"
        Write-Output "Currently in: '$dir'"
        $fileLocation = Join-Path $dir -ChildPath "Program.BuildDate.cs" 
        $placeHolder = "BUILD-DATE-ATTRIBUTE"
        (get-content $fileLocation) | foreach-object {$_ -replace $placeHolder, $buildDateAttribute} | set-content $fileLocation
        Write-Output "BuildDateAttribute written..."
        Write-Output "==============================================================================================================================================="

    - name: Patch CommitIdAttribute
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      shell: powershell
      run: |
        Write-Output "==============================================================================================================================================="
        Write-Output "Pre build. Patching CommitId Attribute..."
        Write-Output "==============================================================================================================================================="
        $commitIdAttribute = git log --format="%H" -n 1
        Write-Output "Using: '$commitIdAttribute'"
        $dir = "./src/${{ env.APP_DIR }}"
        Write-Output "Currently in: '$dir'"
        $fileLocation = Join-Path $dir -ChildPath "Program.CommitId.cs" 
        $placeHolder = "COMMIT-ID-ATTRIBUTE"
        (get-content $fileLocation) | foreach-object {$_ -replace $placeHolder, $commitIdAttribute} | set-content $fileLocation
        Write-Output "CommitIdAttribute written..."
        Write-Output "==============================================================================================================================================="

    - name: Release Build (Check)
      if: (github.ref != 'refs/heads/main' && !inputs.fullbuild)
      run: dotnet build "./src" --configuration Release
    
    - name: Release Build with Version (Full Build)
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      run: dotnet build "./src" --configuration Release -p:Version=${{ steps.gitversion.outputs.MajorMinorPatch }} -p:FileVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}

    - name: Decode Code-Signing Pfx
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      working-directory: "./src"
      shell: powershell
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path . -ChildPath ${{ secrets.PFX_CERT_FILENAME }}
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Sign Application Files (Post Build)
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      working-directory: "./src"
      shell: powershell
      run: |
        $signFiles = @("EM.HostsManager.dll", "EM.HostsManager.App.exe", "EM.HostsManager.App.dll")
        $signDir = "${{ env.APP_DIR }}\bin\${{ env.BUILD_CONFIG }}\${{ env.DOTNET_VER }}\"
        $signArgs = " sign /f '${{ secrets.PFX_CERT_FILENAME }}' /p '${{ secrets.Pfx_Password }}' /t '${{ env.TIMESTAMP_URL }}' /fd sha256 "
        Foreach ($fileToSign in $signFiles)
        {
          $signArgsAndFile = $signArgs + "'" + $signDir + $fileToSign + "'"
          $signCmd = "cmd /c '${{ env.SIGNTOOL }}' " + $signArgsAndFile
          Invoke-Expression $signCmd
        }
        
    - name: Install Inno Setup
      shell: cmd
      run: |
        choco install innosetup

    - name: Build Installer
      working-directory: "./src/${{ env.INSTALLER_DIR }}"
      run: |
        iscc.exe EM.HostsManager.Installer.iss /DInstallerVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}

    - name: Sign Installer (Post Build)
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      working-directory: "./src"
      shell: powershell
      run: |
        $signFiles = @("EM.HostsManager.Installer.${{ steps.gitversion.outputs.MajorMinorPatch }}.exe")
        $signDir = "${{ env.INSTALLER_DIR }}\Output\"
        $signArgs = " sign /f '${{ secrets.PFX_CERT_FILENAME }}' /p '${{ secrets.Pfx_Password }}' /t '${{ env.TIMESTAMP_URL }}' /fd sha256 "
        Foreach ($fileToSign in $signFiles)
        {
          $signArgsAndFile = $signArgs + "'" + $signDir + $fileToSign + "'"
          $signCmd = "cmd /c '${{ env.SIGNTOOL }}' " + $signArgsAndFile
          Invoke-Expression $signCmd
        }

    - name: Clean up (Code Signing Pfx)
      if: ((github.ref == 'refs/heads/main' || inputs.fullbuild) && success() || failure())
      shell: powershell
      working-directory: "./src"
      continue-on-error: true
      run: Remove-Item -Verbose -Path ${{ secrets.PFX_CERT_FILENAME }}

    - name: Copy Build Files (1 of 3)
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      shell: cmd
      working-directory: "./src"
      run: |
        if not exist Binaries mkdir Binaries
        copy "${{ env.APP_DIR }}\bin\${{ env.BUILD_CONFIG }}\${{ env.DOTNET_VER }}\*.*" "Binaries"

    - name: Copy Build Files (2 of 3)
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      shell: cmd
      working-directory: "./src"
      run: |
        cd Binaries
        if not exist Deploy mkdir Deploy
        cd ..
        copy "${{ env.APP_DIR }}\bin\${{ env.BUILD_CONFIG }}\${{ env.DOTNET_VER }}\EM.HostsManager.dll" "Binaries\Deploy"
        copy "${{ env.APP_DIR }}\bin\${{ env.BUILD_CONFIG }}\${{ env.DOTNET_VER }}\EM.HostsManager.App.exe" "Binaries\Deploy"
        copy "${{ env.APP_DIR }}\bin\${{ env.BUILD_CONFIG }}\${{ env.DOTNET_VER }}\EM.HostsManager.App.ico" "Binaries\Deploy"
        copy "${{ env.APP_DIR }}\bin\${{ env.BUILD_CONFIG }}\${{ env.DOTNET_VER }}\EM.HostsManager.App.dll" "Binaries\Deploy"
        copy "${{ env.APP_DIR }}\bin\${{ env.BUILD_CONFIG }}\${{ env.DOTNET_VER }}\EM.HostsManager.App.runtimeconfig.json" "Binaries\Deploy"
        copy "${{ env.APP_DIR }}\bin\${{ env.BUILD_CONFIG }}\${{ env.DOTNET_VER }}\Microsoft.Extensions.DependencyInjection.dll" "Binaries\Deploy"
        copy "${{ env.APP_DIR }}\bin\${{ env.BUILD_CONFIG }}\${{ env.DOTNET_VER }}\Microsoft.Extensions.DependencyInjection.Abstractions.dll" "Binaries\Deploy"

    - name: Copy Build Files (3 of 3)
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      shell: cmd
      working-directory: "./src"
      run: |
        cd Binaries
        if not exist Installer mkdir Installer
        cd ..
        copy "${{ env.INSTALLER_DIR }}\Output" "Binaries\Installer"

    # Right now I'm manually tagging the repo for this project.
    # This may change in the future.
    #
    #- name: Tag Repo
    #  if: github.ref == 'refs/heads/main'
    #  shell: powershell
    #  run: |
    #    git tag "v${{steps.gitversion.outputs.MajorMinorPatch}}"
    #    git push --force --tags origin

    - name: Publish build artifacts
      if: (github.ref == 'refs/heads/main' || inputs.fullbuild)
      uses: actions/upload-artifact@v4
      with:
        name: EM.HostsManager-${{steps.gitversion.outputs.MajorMinorPatch}}
        path: "./src/Binaries"
